import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import "./style.css";

type Client = Record<string, any>;
type Snapshot = { clients: Client[]; monitors: Record<string, any>[]; workspaces: Record<string, any>[]; active: Client };
let data: Snapshot = { clients: [], monitors: [], workspaces: [], active: {} };
let selected = "";
let paused = false;
const events: string[] = [];
const app = document.querySelector<HTMLDivElement>("#app")!;
const settings = new URLSearchParams(location.search).has("settings") || (window as Window & { __HYPR_INSPECTOR_SETTINGS__?: boolean }).__HYPR_INSPECTOR_SETTINGS__ === true;
const release = Number(import.meta.env.VITE_INSPECTOR_RELEASE || "1.0");
const atLeast = (version: number) => release >= version;

const esc = (value: unknown) => String(value ?? "—").replace(/[&<>\"]/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[c]!));
const tag = (text: string, tone = "") => `<span class="tag ${tone}">${esc(text)}</span>`;
const address = (c: Client) => String(c.address || "").slice(-6).toUpperCase();

function shell() {
  if (settings) { renderSettings(); return; }
  app.innerHTML = `
    <main class="frame">
      <header><div class="brand"><span class="sigil">◈</span><div><h1>HYPRLAND <b>INSPECTOR</b></h1><p>LIVE COMPOSITOR OBSERVABILITY CONSOLE · v${release.toFixed(1)}</p></div></div><div class="header-status"><i></i><span id="connection">CONNECTING</span><button id="refresh" title="Refresh">↻</button>${atLeast(.9) ? '<button id="open-settings" title="Settings">⚙</button>' : ""}<button class="window-control" id="minimize">—</button><button class="window-control danger" id="close">×</button></div></header>
      <nav><button class="nav active" data-view="overview">OVERVIEW</button>${atLeast(.7) ? '<button class="nav" data-view="rules">RULE LAB</button>' : ""}${atLeast(.6) ? '<button class="nav" data-view="events">EVENT STREAM <em id="event-count">0</em></button>' : ""}${atLeast(.8) ? '<button class="nav" data-view="diagnose">WHY HERE?</button>' : ""}</nav>
      <section id="content"></section>
      <footer><span>HYPRLAND IPC / SOCKET2</span><span id="footer-state">WAITING FOR COMPOSITOR</span><span>F1 HELP · ESC CLOSE</span></footer>
    </main>`;
  document.querySelectorAll<HTMLButtonElement>(".nav").forEach(b => b.onclick = () => { document.querySelector(".nav.active")?.classList.remove("active"); b.classList.add("active"); render(b.dataset.view!); });
  document.querySelector("#refresh")!.addEventListener("click", refresh);
  document.querySelector("#open-settings")?.addEventListener("click", () => renderSettings());
  document.querySelector("#close")!.addEventListener("click", () => getCurrentWindow().close());
  document.querySelector("#minimize")!.addEventListener("click", () => getCurrentWindow().minimize());
  render("overview");
}

function render(view: string) { ({ overview: renderOverview, rules: renderRules, events: renderEvents, diagnose: renderDiagnose } as Record<string, () => void>)[view](); }

function renderOverview() {
  const content = document.querySelector("#content")!;
  const early = `<section class="panel quick"><div class="panel-head"><span>COMPOSITOR CONNECTION</span><small>v0.1 FOUNDATION</small></div><div class="details"><h2>${data.active?.class ? "HYPRLAND ONLINE" : "AWAITING HYPRLAND"}</h2><p>${data.active?.title ? esc(data.active.title) : "The inspector will show the currently focused window once Hyprland IPC responds."}</p></div></section>`;
  const topology = `<section class="panel map"><div class="panel-head"><span>${atLeast(.5) ? "MONITOR / WORKSPACE TOPOLOGY" : atLeast(.4) ? "MONITOR MAP" : "WORKSPACE MAP"}</span><small>${atLeast(.4) ? data.monitors.length + " OUTPUTS" : data.workspaces.length + " WORKSPACES"}</small></div><div class="monitor-grid">${atLeast(.4) ? data.monitors.map((m, i) => monitorCard(m, i)).join("") || empty("No monitor information available") : data.workspaces.map(w => `<div class="monitor"><div class="monitor-title"><span>WORKSPACE</span>${tag(w.name)}</div><div class="screen"><div class="resolution">${esc(w.monitor || "UNASSIGNED")}</div><div class="window-dots">${data.clients.filter(c => c.workspace?.id === w.id).map(() => "<b></b>").join("")}</div></div></div>`).join("") || empty("No workspace information available")}</div></section>`;
  content.innerHTML = `<div class="dashboard">${atLeast(.3) ? topology : early}<aside class="stats">${atLeast(.2) ? `<div class="stat"><strong>${data.clients.length}</strong><span>OPEN WINDOWS</span></div><div class="stat"><strong>${data.clients.filter(c => c.floating).length}</strong><span>FLOATING</span></div>` : ""}${atLeast(.3) ? `<div class="stat"><strong>${data.workspaces.length}</strong><span>WORKSPACES</span></div>` : ""}<div class="stat active-stat"><strong>${esc(data.active?.class || "NONE")}</strong><span>ACTIVE CLIENT</span></div></aside>${atLeast(.2) ? `<section class="panel clients"><div class="panel-head"><span>LIVE WINDOW INVENTORY</span><small>SELECT A CLIENT TO INSPECT</small></div><div class="client-list">${data.clients.map(clientRow).join("") || empty("No clients reported by Hyprland")}</div></section>` : ""}<section class="panel quick"><div class="panel-head"><span>ACTIVE WINDOW</span><small>LIVE</small></div>${clientDetails(data.active || {})}</section></div>`;
  content.querySelectorAll<HTMLElement>(".client-row").forEach(row => row.onclick = () => { selected = row.dataset.address!; document.querySelectorAll(".client-row").forEach(x => x.classList.remove("selected")); row.classList.add("selected"); });
}

function monitorCard(m: Record<string, any>, index: number) {
  const ws = data.workspaces.filter(w => w.monitorID === m.id || w.monitor === m.name);
  const wins = data.clients.filter(c => c.monitor === m.id || c.monitor === m.name);
  return `<article class="monitor ${m.focused ? "focused" : ""}"><div class="monitor-title"><span>DISPLAY 0${index + 1}</span>${tag(m.name || "UNKNOWN", "cyan")}</div><div class="screen"><div class="resolution">${m.width} × ${m.height}</div><div class="workspace-tabs">${ws.map(w => `<span class="workspace ${w.id === m.activeWorkspace?.id ? "current" : ""}">${esc(w.name)}</span>`).join("") || "<span>NO WORKSPACE</span>"}</div><div class="window-dots">${wins.slice(0, 12).map(c => `<b title="${esc(c.title)}"></b>`).join("")}</div></div><div class="monitor-meta">${m.focused ? "◉ FOCUSED" : "○ ONLINE"}<span>${m.refreshRate ? Math.round(m.refreshRate) + "HZ" : "—"}</span></div></article>`;
}
function clientRow(c: Client) { return `<article class="client-row ${c.address === data.active?.address ? "active" : ""}" data-address="${esc(c.address)}"><span class="client-index">${address(c)}</span><div><strong>${esc(c.class || "unknown")}</strong><small>${esc(c.title || "untitled")}</small></div><div class="client-tags">${tag("WS " + (c.workspace?.name ?? "?"))}${c.floating ? tag("FLOAT", "warn") : ""}</div><span class="chevron">›</span></article>`; }
function clientDetails(c: Client) { if (!c.address) return empty("No active window"); return `<div class="details"><h2>${esc(c.class)}</h2><p>${esc(c.title)}</p><div class="kv"><span>ADDRESS</span><code>${esc(c.address)}</code><span>WORKSPACE</span><b>${esc(c.workspace?.name)}</b><span>MONITOR</span><b>${esc(c.monitor)}</b><span>POSITION</span><b>[${(c.at || []).join(", ")}]</b></div></div>`; }
function empty(message: string) { return `<div class="empty">◇ ${esc(message)}</div>`; }

function renderRules() {
  const client = data.clients.find(c => c.address === selected) || data.active || {};
  const content = document.querySelector("#content")!;
  content.innerHTML = `<div class="rule-layout"><section class="panel rule-form"><div class="panel-head"><span>WINDOW RULE GENERATOR</span><small>HYPRLAND V2 SYNTAX</small></div><p class="hint">Build a precise rule from a live client. Generated rules use current Hyprland window-rule matching fields.</p><label>TARGET CLIENT<select id="rule-client">${data.clients.map(c => `<option value="${esc(c.address)}" ${c.address === client.address ? "selected" : ""}>${esc(c.class)} — ${esc(c.title)}</option>`).join("")}</select></label><div class="form-grid"><label>MATCH BY<select id="match-field"><option value="class">class</option><option value="title">title</option><option value="initialClass">initialClass</option></select></label><label>ACTION<select id="rule-action"><option value="float">float</option><option value="center">center</option><option value="pin">pin</option><option value="workspace">workspace</option><option value="size">size</option><option value="opacity">opacity</option></select></label></div><label>VALUE<input id="rule-value" placeholder="optional action value, e.g. 3 or 800 600" /></label><button class="primary" id="generate">GENERATE RULE <span>→</span></button></section><section class="panel output"><div class="panel-head"><span>MATCH PREVIEW</span><small id="match-count">—</small></div><div id="rule-preview" class="code-output"></div><div class="panel-head minor"><span>LIVE MATCHES</span></div><div id="rule-matches" class="match-list"></div></section></div>`;
  const update = () => { const c = data.clients.find(x => x.address === (document.querySelector<HTMLSelectElement>("#rule-client")!).value) || {}; const field = (document.querySelector<HTMLSelectElement>("#match-field")!).value; const action = (document.querySelector<HTMLSelectElement>("#rule-action")!).value; const value = (document.querySelector<HTMLInputElement>("#rule-value")!).value.trim(); const match = field === "title" ? c.title : field === "initialClass" ? (c.initialClass || c.class) : c.class; const condition = `${field}:${match ? "^(" + match.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + ")$" : ""}`; document.querySelector("#rule-preview")!.textContent = `windowrule = ${action}${value ? " " + value : ""}, match:${condition}`; const matches = data.clients.filter(x => String(field === "title" ? x.title : field === "initialClass" ? (x.initialClass || x.class) : x.class) === String(match)); document.querySelector("#match-count")!.textContent = `${matches.length} CLIENT${matches.length === 1 ? "" : "S"} MATCH`; document.querySelector("#rule-matches")!.innerHTML = matches.map(clientRow).join("") || empty("No matching live client"); };
  content.querySelectorAll("select,input").forEach(el => el.addEventListener("input", update)); document.querySelector("#generate")!.addEventListener("click", update); update();
}

function renderEvents() { const content = document.querySelector("#content")!; content.innerHTML = `<div class="event-layout"><section class="panel stream"><div class="panel-head"><span>COMPOSITOR EVENT STREAM</span><div><button id="pause">${paused ? "RESUME" : "PAUSE"}</button><button id="clear">CLEAR</button></div></div><div class="event-log">${events.map((event, i) => `<div><time>${String(events.length-i).padStart(3,"0")}</time><span class="event-kind">${esc(event.split(">>")[0])}</span><code>${esc(event.split(">>").slice(1).join(">>"))}</code></div>`).join("") || empty("Listening on Hyprland socket2…")}</div></section><aside class="panel legend"><div class="panel-head"><span>SIGNAL GUIDE</span></div><p><b>openwindow</b> client created</p><p><b>movewindow</b> client moved</p><p><b>workspace</b> workspace changed</p><p><b>activewindow</b> focus changed</p></aside></div>`; content.querySelector("#pause")!.addEventListener("click", () => { paused = !paused; renderEvents(); }); content.querySelector("#clear")!.addEventListener("click", () => { events.length = 0; renderEvents(); }); }

function renderDiagnose() { const c = data.clients.find(x => x.address === selected) || data.active || {}; const content = document.querySelector("#content")!; const reasons = c.address ? [["CLIENT IDENTITY", `${c.class || "unknown"} / ${c.initialClass || c.class || "unknown"}`], ["PLACED ON", `Workspace ${c.workspace?.name ?? "?"} · Monitor ${c.monitor ?? "?"}`], ["GEOMETRY", `at [${(c.at || []).join(", ")}] · ${((c.size || []).join(" × "))}`], ["WINDOW STATE", `${c.floating ? "Floating" : "Tiled"}${c.fullscreen ? " · Fullscreen" : ""}${c.pinned ? " · Pinned" : ""}`], ["RULE EVIDENCE", "Hyprland does not expose applied rule provenance. This view derives the final state from live IPC."]]: []; content.innerHTML = `<div class="diagnose"><section class="panel diagnosis"><div class="panel-head"><span>WHY IS THIS WINDOW HERE?</span><small>STATE-BASED DIAGNOSTIC</small></div>${c.address ? `<div class="diagnose-target">${clientRow(c)}</div><ol>${reasons.map(([label, value], i) => `<li><span>${String(i+1).padStart(2,"0")}</span><div><small>${label}</small><strong>${esc(value)}</strong></div></li>`).join("")}</ol><div class="notice">◇ To trace a placement rule, use the Rule Lab to generate a matching condition, then compare it with your Hyprland config. Hyprland's IPC supplies outcomes, not a rule execution trace.</div>` : empty("Select or focus a Hyprland window to diagnose its placement.")}</section></div>`; }

function renderSettings() { app.innerHTML = `<main class="settings frame"><header><div class="brand"><span class="sigil">◈</span><div><h1>INSPECTOR <b>SETTINGS</b></h1><p>LOCAL PREFERENCES</p></div></div><div class="header-status"><button class="window-control danger" id="close-settings">×</button></div></header><section class="settings-body"><div class="panel"><div class="panel-head"><span>REFRESH BEHAVIOUR</span></div><label class="toggle"><input id="auto-refresh" type="checkbox" checked /> <span>LIVE SNAPSHOT REFRESH</span><small>Reload compositor state whenever a Hyprland event arrives.</small></label><label class="toggle"><input type="checkbox" checked /> <span>AUTO-SCROLL EVENT STREAM</span><small>Keep recent compositor activity visible.</small></label></div><div class="panel"><div class="panel-head"><span>ABOUT</span></div><p class="hint">Hyprland Inspector is a local-only diagnostic interface. It reads the Hyprland IPC socket and runs read-only <code>hyprctl -j</code> queries.</p></div></section></main>`; document.querySelector("#close-settings")!.addEventListener("click", () => getCurrentWindow().close()); }

async function refresh() { try { data = await invoke<Snapshot>("snapshot"); document.querySelector("#connection")!.textContent = "CONNECTED"; document.querySelector("#footer-state")!.textContent = `${data.clients.length} CLIENTS · LIVE`; const active = document.querySelector<HTMLButtonElement>(".nav.active")?.dataset.view || "overview"; render(active); } catch (err) { document.querySelector("#connection")!.textContent = "OFFLINE"; document.querySelector("#footer-state")!.textContent = String(err); } }

shell();
if (!settings) { listen<string>("hypr-event", event => { if (!paused) { events.unshift(event.payload); events.splice(200); const count = document.querySelector("#event-count"); if (count) count.textContent = String(events.length); if (document.querySelector(".nav.active")?.getAttribute("data-view") === "events") renderEvents(); refresh(); } }); refresh(); setInterval(refresh, 5000); }
